export const initialProfiles = [
    {
      id: 1,
      name: 'John Doe',
      description: 'Software Engineer',
      address: '1600 Amphitheatre Parkway, Mountain View, CA',
      lat: 37.42216,
      lng: -122.08427,
    },
    {
      id: 2,
      name: 'Jane Smith',
      description: 'Graphic Designer',
      address: '1 Infinite Loop, Cupertino, CA',
      lat: 37.33182,
      lng: -122.03118,
    },
    {
        id: 3,
        name: "Mike Johnson",
        description: "Graphic Designer at Creative Studios",
        address: "350 Fifth Avenue, New York, NY",
        lat: 40.748817,
        lng: -73.985428,
      },
      {
        id: 4,
        name: "Emily Davis",
        description: "Marketing Specialist at GlobalMarketing",
        address: "2001 Market Street, San Francisco, CA",
        lat: 37.774929,
        lng: -122.419418,
      },
      {
        id: 5,
        name: "David Brown",
        description: "Data Scientist at DataWorks",
        address: "1 Hacker Way, Menlo Park, CA",
        lat: 37.484731,
        lng: -122.147708,
      },
      {
        id: 6,
        name: "Sophia Miller",
        description: "UX/UI Designer at DesignLab",
        address: "42 Wallaby Way, Sydney, Australia",
        lat: -33.867850,
        lng: 151.209290,
      },
      {
        id: 7,
        name: "James Wilson",
        description: "Full Stack Developer at WebDev Co.",
        address: "350 Park Avenue, New York, NY",
        lat: 40.757975,
        lng: -73.985542,
      },
      {
        id: 8,
        name: "Olivia Taylor",
        description: "Business Analyst at FinTech Ltd.",
        address: "500 Tech Drive, Austin, TX",
        lat: 30.267153,
        lng: -97.743061,
      }
  ];